baseurl = "https://the-creative-craft.github.io/"
title = "Creative Craft"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "pink"
  description = ["Welcome to CREATIVE CRAFT's Creative Corner, where the artistry of crochet and the elegance of resin craftsmanship come together to bring you a unique collection of handcrafted treasures.",
"Indulge in the enchanting world of crochet with our meticulously crafted purses, each stitch a testament to the dedication and skill poured into every creation. Our resin masterpieces elevate everyday items into extraordinary works of art, transforming simple coasters into stunning conversation pieces and framing your cherished memories in exquisite photo frames."]
  copyright = "&copy;2020 Creative Craft"
  sidebarAbout = [
    "Meet the creative soul behind Amatullah Banswara's Creative Corner, hailing from the vibrant city of Ratlam in Madhya Pradesh, India. As a proud Indian girl, I've poured seven years of passion into crafting unique treasures that blend the rich tradition of crochet with the modern allure of resin.",
    "From intricately stitched purses to enchanting resin-coated coasters, each piece reflects my love for the artistry that has been woven into the fabric of my life. Join me on this journey of creativity at Amatullah's Creative Corner, where tradition meets contemporary charm, and every creation tells a story of dedication and timeless beauty."]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "amatullabanswara65@gmail.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  email         = "amatullabanswara65@gmail.com"
  instagram     = "https://www.instagram.com/the_creative_crafts_/"
